---
output:
  pdf_document:
    extra_dependencies: 
      array: NULL
      caption: NULL
      graphicx: NULL
      siunitx: NULL
      colortbl : NULL
      multirow: NULL
      hhline: NULL
      calc: NULL
      threeparttable: NULL
      tabularx: NULL
      wrapfig: NULL
      hyperref: NULL
      placeins: NULL
    keep_tex: true
geometry: margin=1cm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,warning = F,message = F)
```

```{=latex}

\definecolor{mypink1}{RGB}{202, 200, 72}
\setlength{\footskip}{-1pt}
\definecolor{titlecolor}{RGB}{86,193,166}
\colorlet{shadecolor}{gray!40}

```

```{=latex}

\newgeometry{left=2.5cm, right=2cm,bottom = 3cm}

\begin{titlepage} % Suppresses displaying the page number on the title page and the subsequent page counts as page 1


	
	%------------------------------------------------
	%	Grey title box
	%------------------------------------------------
	
	\colorbox{titlecolor}{
		\parbox[t]{0.93\textwidth}{ % Outer full width box
			\parbox[t]{0.91\textwidth}{ % Inner box for inner right text margin
				\raggedleft % Right align the text
				\fontsize{50pt}{80pt}\selectfont % Title font size, the first argument is the font size and the second is the line spacing, adjust depending on title length
				\vspace{0.7cm} % Space between the start of the title and the top of the grey box
				
				Study Title\\
				and\\
				Information\\
			 \vspace{4cm}
			
				Codebook for dataset\\
				
				\vspace{0.7cm} % Space between the end of the title and the bottom of the grey box
			}
		}
	}
	
	\vfill % Space between the title box and author information
	
	%------------------------------------------------
	%	Author name and information
	%------------------------------------------------
	
	\parbox[t]{0.93\textwidth}{ % Box to inset this section slightly
		\raggedleft % Right align the text
		\Large % Increase the font size
		{\Large B.J. Blazkowicz}\\[4pt] % Extra space after name
		Department Name\\
		Institution Name\\[4pt] % Extra space before URL
		\texttt{LaTeXTemplates.com}\\
		
		\hfill\rule{0.2\linewidth}{1pt}% Horizontal line, first argument width, second thickness
	}
	
\end{titlepage}

\restoregeometry
\setlength{\footskip}{-1pt}

```




```{r}

library(codebook)
library(gtsummary)
library(sjlabelled)
library(kableExtra)
library(gt)
# library(gtExtras)
library(huxtable)
library(readxl)


header_beam = function(varname){
cat("\\colorbox{mypink1}{\\makebox[\\textwidth]{\\strut\\bfseries\\color{black} ",varname,"}}")
}

'%!in%' <- function(x,y)!('%in%'(x,y))

knit_function = function(knit_object){
  paste(knitr::knit(text = knit_object), collapse = '\n')
}




# define exactly where the meta file is located 
meta_path = 


# global options 
options(huxtable.bookdown = T)
options(knitr.duplicate.label = "allow")

```



```{r}

# read the meta file data in 
meta_data <- readxl::read_excel(meta_path) |>
  dplyr::select(-starts_with("NA")) |> tibble::as_tibble()


# read in the datafile
dataset = 

```




```{r results='asis'}
# this is for the first wave of variables
variable_names = 
variable_labels = 
  
  
# generate the mini table of contents for this set of variables 
page_numbers = c()

for(name in variable_names){
  page_numbers = c(paste0("Page ","\\pageref{",name,"} \n"),page_numbers)
}

toc_code = data.frame(
  variable_name = variable_names,
  variable_label = variable_labels,
  pages = rev(page_numbers)
) |>
  dplyr::rename(
  "Variable Name"  = variable_name,
  "Variable Label" = variable_label,
  "Page Number" = pages
  ) |> 
  huxtable() |>
  set_position("center") |> 
  theme_grey() |> 
  to_latex(tabular_only = T) 




toc_code = gsub(pattern = '$\\backslash$pageref\\',replacement = '\\pageref',toc_code,fixed = T)


for(name in variable_names){

tofind = gsub(pattern = "\n",replacement = "",commonmark::markdown_latex(name))
toc_code = gsub(pattern = paste0(tofind,"\\"),replacement = name,toc_code,fixed = T)
    
}

toc_code |> cat()


```


\newpage


```{r}

# generate the info for the first wave of variables

list_to_knit = lapply(
  variable_names,
  FUN = chokmah::gen_codebook,
  meta_data = meta_data,
  dataset = dataset
)



```


`r unlist(lapply(list_to_knit,knit_function))`
